// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/snet.proto

package com.marshmallow.snet.service.protobuf;

/**
 * Protobuf enum {@code ClientType}
 */
public enum ClientType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ADMIN = 0;</code>
   */
  ADMIN(0),
  /**
   * <code>NODE = 1;</code>
   */
  NODE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ADMIN = 0;</code>
   */
  public static final int ADMIN_VALUE = 0;
  /**
   * <code>NODE = 1;</code>
   */
  public static final int NODE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClientType valueOf(int value) {
    return forNumber(value);
  }

  public static ClientType forNumber(int value) {
    switch (value) {
      case 0: return ADMIN;
      case 1: return NODE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClientType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClientType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClientType>() {
          public ClientType findValueByNumber(int number) {
            return ClientType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.marshmallow.snet.service.protobuf.Snet.getDescriptor().getEnumTypes().get(1);
  }

  private static final ClientType[] VALUES = values();

  public static ClientType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ClientType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ClientType)
}

