// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/snet.proto

package com.marshmallow.snet.service.protobuf;

public interface InfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoRequest)
    com.google.protobuf.MessageOrBuilder {
}
