// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/snet.proto

package com.marshmallow.snet.service.protobuf;

public interface InitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.ClientType type = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.ClientType getType();

  /**
   * <code>int32 address = 2;</code>
   */
  int getAddress();
}
