// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/snet.proto

package com.marshmallow.snet.service.protobuf;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();

  /**
   * <code>int32 sequence = 2;</code>
   */
  int getSequence();

  /**
   * <code>.Packet.Type type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.Packet.Type type = 3;</code>
   */
  com.marshmallow.snet.service.protobuf.Packet.Type getType();

  /**
   * <code>int32 source = 4;</code>
   */
  int getSource();

  /**
   * <code>int32 destination = 5;</code>
   */
  int getDestination();

  /**
   * <code>bytes payload = 6;</code>
   */
  com.google.protobuf.ByteString getPayload();
}
