// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/snet.proto

package com.marshmallow.snet.service.protobuf;

public interface RxConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RxConfig)
    com.google.protobuf.MessageOrBuilder {
}
