// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/snet.proto

package com.marshmallow.snet.service.protobuf;

public interface RxRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RxRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 address = 1;</code>
   */
  int getAddress();
}
