// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/snet.proto

package com.marshmallow.snet.service.protobuf;

public interface TxConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TxConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Packet packet = 1;</code>
   */
  boolean hasPacket();
  /**
   * <code>.Packet packet = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.Packet getPacket();
  /**
   * <code>.Packet packet = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.PacketOrBuilder getPacketOrBuilder();
}
