// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snet.proto

package com.marshmallow.snet.service.protobuf;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .Status status = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.Status getStatus();

  /**
   * <code>repeated int32 addresses = 3;</code>
   */
  java.util.List<java.lang.Integer> getAddressesList();
  /**
   * <code>repeated int32 addresses = 3;</code>
   */
  int getAddressesCount();
  /**
   * <code>repeated int32 addresses = 3;</code>
   */
  int getAddresses(int index);
}
