// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snet.proto

package com.marshmallow.snet.service.protobuf;

/**
 * Protobuf type {@code Packet}
 */
public  final class Packet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Packet)
    PacketOrBuilder {
  // Use Packet.newBuilder() to construct.
  private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Packet() {
    length_ = 0;
    sequence_ = 0;
    type_ = 0;
    source_ = 0;
    destination_ = 0;
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Packet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            length_ = input.readInt32();
            break;
          }
          case 16: {

            sequence_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 32: {

            source_ = input.readInt32();
            break;
          }
          case 40: {

            destination_ = input.readInt32();
            break;
          }
          case 50: {

            payload_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.marshmallow.snet.service.protobuf.Snet.internal_static_Packet_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.marshmallow.snet.service.protobuf.Snet.internal_static_Packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.marshmallow.snet.service.protobuf.Packet.class, com.marshmallow.snet.service.protobuf.Packet.Builder.class);
  }

  /**
   * Protobuf enum {@code Packet.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DATA = 0;</code>
     */
    DATA(0),
    /**
     * <code>COMMAND = 1;</code>
     */
    COMMAND(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DATA = 0;</code>
     */
    public static final int DATA_VALUE = 0;
    /**
     * <code>COMMAND = 1;</code>
     */
    public static final int COMMAND_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return DATA;
        case 1: return COMMAND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.marshmallow.snet.service.protobuf.Packet.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Packet.Type)
  }

  public static final int LENGTH_FIELD_NUMBER = 1;
  private int length_;
  /**
   * <code>optional int32 length = 1;</code>
   */
  public int getLength() {
    return length_;
  }

  public static final int SEQUENCE_FIELD_NUMBER = 2;
  private int sequence_;
  /**
   * <code>optional int32 sequence = 2;</code>
   */
  public int getSequence() {
    return sequence_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>optional .Packet.Type type = 3;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .Packet.Type type = 3;</code>
   */
  public com.marshmallow.snet.service.protobuf.Packet.Type getType() {
    com.marshmallow.snet.service.protobuf.Packet.Type result = com.marshmallow.snet.service.protobuf.Packet.Type.valueOf(type_);
    return result == null ? com.marshmallow.snet.service.protobuf.Packet.Type.UNRECOGNIZED : result;
  }

  public static final int SOURCE_FIELD_NUMBER = 4;
  private int source_;
  /**
   * <code>optional int32 source = 4;</code>
   */
  public int getSource() {
    return source_;
  }

  public static final int DESTINATION_FIELD_NUMBER = 5;
  private int destination_;
  /**
   * <code>optional int32 destination = 5;</code>
   */
  public int getDestination() {
    return destination_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString payload_;
  /**
   * <code>optional bytes payload = 6;</code>
   */
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (length_ != 0) {
      output.writeInt32(1, length_);
    }
    if (sequence_ != 0) {
      output.writeInt32(2, sequence_);
    }
    if (type_ != com.marshmallow.snet.service.protobuf.Packet.Type.DATA.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (source_ != 0) {
      output.writeInt32(4, source_);
    }
    if (destination_ != 0) {
      output.writeInt32(5, destination_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(6, payload_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (length_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, length_);
    }
    if (sequence_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, sequence_);
    }
    if (type_ != com.marshmallow.snet.service.protobuf.Packet.Type.DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (source_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, source_);
    }
    if (destination_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, destination_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, payload_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.marshmallow.snet.service.protobuf.Packet)) {
      return super.equals(obj);
    }
    com.marshmallow.snet.service.protobuf.Packet other = (com.marshmallow.snet.service.protobuf.Packet) obj;

    boolean result = true;
    result = result && (getLength()
        == other.getLength());
    result = result && (getSequence()
        == other.getSequence());
    result = result && type_ == other.type_;
    result = result && (getSource()
        == other.getSource());
    result = result && (getDestination()
        == other.getDestination());
    result = result && getPayload()
        .equals(other.getPayload());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getLength();
    hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
    hash = (53 * hash) + getSequence();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource();
    hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getDestination();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.marshmallow.snet.service.protobuf.Packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.marshmallow.snet.service.protobuf.Packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Packet)
      com.marshmallow.snet.service.protobuf.PacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.marshmallow.snet.service.protobuf.Snet.internal_static_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.marshmallow.snet.service.protobuf.Snet.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.marshmallow.snet.service.protobuf.Packet.class, com.marshmallow.snet.service.protobuf.Packet.Builder.class);
    }

    // Construct using com.marshmallow.snet.service.protobuf.Packet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      length_ = 0;

      sequence_ = 0;

      type_ = 0;

      source_ = 0;

      destination_ = 0;

      payload_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.marshmallow.snet.service.protobuf.Snet.internal_static_Packet_descriptor;
    }

    public com.marshmallow.snet.service.protobuf.Packet getDefaultInstanceForType() {
      return com.marshmallow.snet.service.protobuf.Packet.getDefaultInstance();
    }

    public com.marshmallow.snet.service.protobuf.Packet build() {
      com.marshmallow.snet.service.protobuf.Packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.marshmallow.snet.service.protobuf.Packet buildPartial() {
      com.marshmallow.snet.service.protobuf.Packet result = new com.marshmallow.snet.service.protobuf.Packet(this);
      result.length_ = length_;
      result.sequence_ = sequence_;
      result.type_ = type_;
      result.source_ = source_;
      result.destination_ = destination_;
      result.payload_ = payload_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.marshmallow.snet.service.protobuf.Packet) {
        return mergeFrom((com.marshmallow.snet.service.protobuf.Packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.marshmallow.snet.service.protobuf.Packet other) {
      if (other == com.marshmallow.snet.service.protobuf.Packet.getDefaultInstance()) return this;
      if (other.getLength() != 0) {
        setLength(other.getLength());
      }
      if (other.getSequence() != 0) {
        setSequence(other.getSequence());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getSource() != 0) {
        setSource(other.getSource());
      }
      if (other.getDestination() != 0) {
        setDestination(other.getDestination());
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.marshmallow.snet.service.protobuf.Packet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.marshmallow.snet.service.protobuf.Packet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int length_ ;
    /**
     * <code>optional int32 length = 1;</code>
     */
    public int getLength() {
      return length_;
    }
    /**
     * <code>optional int32 length = 1;</code>
     */
    public Builder setLength(int value) {
      
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 length = 1;</code>
     */
    public Builder clearLength() {
      
      length_ = 0;
      onChanged();
      return this;
    }

    private int sequence_ ;
    /**
     * <code>optional int32 sequence = 2;</code>
     */
    public int getSequence() {
      return sequence_;
    }
    /**
     * <code>optional int32 sequence = 2;</code>
     */
    public Builder setSequence(int value) {
      
      sequence_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 sequence = 2;</code>
     */
    public Builder clearSequence() {
      
      sequence_ = 0;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .Packet.Type type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .Packet.Type type = 3;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Packet.Type type = 3;</code>
     */
    public com.marshmallow.snet.service.protobuf.Packet.Type getType() {
      com.marshmallow.snet.service.protobuf.Packet.Type result = com.marshmallow.snet.service.protobuf.Packet.Type.valueOf(type_);
      return result == null ? com.marshmallow.snet.service.protobuf.Packet.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .Packet.Type type = 3;</code>
     */
    public Builder setType(com.marshmallow.snet.service.protobuf.Packet.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .Packet.Type type = 3;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int source_ ;
    /**
     * <code>optional int32 source = 4;</code>
     */
    public int getSource() {
      return source_;
    }
    /**
     * <code>optional int32 source = 4;</code>
     */
    public Builder setSource(int value) {
      
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 source = 4;</code>
     */
    public Builder clearSource() {
      
      source_ = 0;
      onChanged();
      return this;
    }

    private int destination_ ;
    /**
     * <code>optional int32 destination = 5;</code>
     */
    public int getDestination() {
      return destination_;
    }
    /**
     * <code>optional int32 destination = 5;</code>
     */
    public Builder setDestination(int value) {
      
      destination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 destination = 5;</code>
     */
    public Builder clearDestination() {
      
      destination_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes payload = 6;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>optional bytes payload = 6;</code>
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes payload = 6;</code>
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Packet)
  }

  // @@protoc_insertion_point(class_scope:Packet)
  private static final com.marshmallow.snet.service.protobuf.Packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.marshmallow.snet.service.protobuf.Packet();
  }

  public static com.marshmallow.snet.service.protobuf.Packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Packet>
      PARSER = new com.google.protobuf.AbstractParser<Packet>() {
    public Packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Packet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Packet> getParserForType() {
    return PARSER;
  }

  public com.marshmallow.snet.service.protobuf.Packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

