// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snet.proto

package com.marshmallow.snet.service.protobuf;

public interface RxResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RxResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .Status status = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.Status getStatus();

  /**
   * <code>optional .Packet packet = 2;</code>
   */
  boolean hasPacket();
  /**
   * <code>optional .Packet packet = 2;</code>
   */
  com.marshmallow.snet.service.protobuf.Packet getPacket();
  /**
   * <code>optional .Packet packet = 2;</code>
   */
  com.marshmallow.snet.service.protobuf.PacketOrBuilder getPacketOrBuilder();
}
