// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snet.proto

package com.marshmallow.snet.service.protobuf;

public interface TxRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TxRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Packet packet = 1;</code>
   */
  boolean hasPacket();
  /**
   * <code>optional .Packet packet = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.Packet getPacket();
  /**
   * <code>optional .Packet packet = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.PacketOrBuilder getPacketOrBuilder();
}
