// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snet.proto

package com.marshmallow.snet.service.protobuf;

public interface TxResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TxResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .Status status = 1;</code>
   */
  com.marshmallow.snet.service.protobuf.Status getStatus();
}
